### ISSUE TITLE
[reactive] Fix WinUI threading issue

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno.extensions#180]

**Comment by nickrandolph** [comment]
@dr1rrb / @jeromelaban was this fixed with the changes I made to the DispatcherQueue (https://github.com/unoplatform/uno.extensions/pull/181), or are there other issues we're seeing?

**Comment by jeromelaban** [comment]
This is still a problem because it requires View Models to be created on the dispatcher. @dr1rrb is working on changing this.

**Comment by nickrandolph** [comment]
@dr1rrb are you tracking the work on threading in Reactive somewhere else? Can we close off this issue as I'm not seeing any threading issues currently affecting the sample apps

**Comment by dr1rrb** [comment]
They have been fixed by https://github.com/unoplatform/uno.extensions/pull/213, I close this
