### ISSUE TITLE
Uno.Extensions.Storage.FileStorage: ReadPackageFileAsync - File 'appsettings.xxxxx.json' does not exist in package 

### ISSUE THREAD

**Issue by guyulmaz** [unoplatform/uno.extensions#2531]
## Current behavior

08-27 12:31:08.772+03:00 I/Uno.Extensions.Storage.FileStorage: ReadPackageFileAsync - File 'appsettings.keyvaluestorageconfiguration.json' does not exist in package 
08-27 12:31:08.823+03:00 I/Uno.Extensions.Storage.FileStorage: ReadPackageFileAsync - File 'appsettings.appconfig.json' does not exist in package 
08-27 12:31:08.826+03:00 I/Uno.Extensions.Storage.FileStorage: ReadPackageFileAsync - File 'appsettings.localizationconfiguration.json' does not exist in package 
08-27 12:31:08.829+03:00 I/Uno.Extensions.Storage.FileStorage: ReadPackageFileAsync - File 'appsettings.localizationsettings.json' does not exist in package 
08-27 12:31:08.832+03:00 I/Uno.Extensions.Storage.FileStorage: ReadPackageFileAsync - File 'appsettings.navigationconfiguration.json' does not exist in package 

## Expected behavior

The template  project does not generate these files , is it possible it generate during project create, if they are necessary ?

## Environment

Nuget Package (s):

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] macOS (AppKit)
- [ ] Mac Catalyst
- [ ] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Skia (WPF)
- [ ] Skia (GTK on Linux/macOS/Windows)
- [ ] Skia (Linux Framebuffer)
- [ ] Build tasks

Visual Studio:

- [ ] 2019 (version: )
- [x ] 2022 (version: )
- [ ] Visual Studio Code (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thanks for the report. This was fixed in https://github.com/unoplatform/uno.extensions/pull/2436 and will be released soon.

**Comment by ptasznikarium** [comment]
This was not fixed, i still get those errors now in 2026, everythyng up to date, new empty project
